models:
  embedding: 'deepseek-r1:1.5b'
  inference: 'deepseek-r1:1.5b'
path:
  emmbeddings: '/datasets/PDFs/deepseek-r1:1.5b/'
  pdfs: '/datasets/PDFs/'
  #pdfs: None
parameters:
  create_embeddings: True
  chunk_size: 500
  chunk_overlap: 100
  
