models:
  embedding: 'deepseek-r1:1.5b'
  inference: 'deepseek-r1:1.5b'
path:
  emmbeddings: '/datasets/deepseek-r1:1.5b'
  #pdfs: '/datasets/packt'
  pdfs: None
parameters:
  create_embeddings: False
  chunk_size: 500
  chunk_overlap: 100
  
