services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rag_client
    working_dir: /app
    volumes:
      - ./:/app
      - ./entrypoint_rag.sh:/entrypoint_rag.sh
      - ${DATASETS_DIR:-./datasets}:/datasets
      - ${MODELS_DIR:-./models}:/models
    environment:
      - BASE_URL=http://ollama:11434
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - JUPYTER_PORT=${JUPYTER_PORT:-8888}
    ports:
      - "7860:7860"
      - "${JUPYTER_PORT:-8888}:${JUPYTER_PORT:-8888}"
    depends_on:
      - ollama
    tty: true
    entrypoint: ["/usr/bin/bash", "/entrypoint_rag.sh"]

volumes:
  ollama_data:
    
    




